# Generated by Django 4.2 on 2025-07-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_userprofile_activation_time_and_more"),
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineOfDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_taken", models.BooleanField(default=False)),
                ("take_time", models.IntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines_of_day",
                        to="medicine.medicine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines_of_day",
                        to="user.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.DeleteModel(
            name="MidicineOfDay",
        ),
    ]
