# Generated by Django 4.2 on 2025-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0002_medicineofday_delete_midicineofday"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
