# Generated by Django 4.2 on 2025-07-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0003_music_audio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicineofday",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="medicineofday",
            name="take_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
