# Generated by Django 4.2 on 2025-07-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0004_alter_medicineofday_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="report",
        ),
        migrations.AddField(
            model_name="music",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
