# Generated by Django 4.2 on 2025-07-25 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatsession",
            name="chat_chatse_user_id_a06e6a_idx",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="character",
        ),
    ]
