# Generated by Django 4.2 on 2025-07-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0001_initial"),
        ("chat", "0002_remove_chatsession_chat_chatse_user_id_a06e6a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="character",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="character.character",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "character"], name="chat_chatse_user_id_a06e6a_idx"
            ),
        ),
    ]
