# Generated by Django 4.2 on 2025-07-24 08:06

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("name", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                ("job", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "activation_time",
                    models.CharField(
                        choices=[
                            ("morning", "🌅 아침 (6~11시)"),
                            ("afternoon", "☀️ 낮 (12~17시)"),
                            ("evening", "🌙 저녁 / 밤 (18~24시)"),
                            ("dawn", "🌃 새벽 (1~5시)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "i_e",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "n_s",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "t_f",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "p_j",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("gmail", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="followers", to="user.userprofile"
                    ),
                ),
            ],
        ),
    ]
