# Generated by Django 4.2 on 2025-07-26 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="activation_time",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="following",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
